name: Deploy Server Trigger

on:
  push:
    branches:
      - prod
    paths:
      - "server/**"
      - "shared/**"
      - "package.json"
      - "package-lock.json"
      - "prod-scripts/deploy-qp-server.sh"
      - ".github/workflows/deploy-server-trigger.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment over SSH
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd /home/ubuntu/webapps/quiz-peers/prod-scripts
            chmod +x deploy-qp-server.sh
            ./deploy-qp-server.sh